# Usamos una versión más moderna de Node.js que soporta tu versión de Prisma
FROM node:22-alpine

# Creamos la carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos de dependencias primero (para optimizar caché)
COPY package*.json ./

# Instalamos las dependencias de Node
RUN npm install

# Copiamos el resto de tu código
COPY . .

# Generamos el cliente de Prisma para que pueda hablar con la base de datos
RUN npx prisma generate

# Exponemos el puerto de tu API
EXPOSE 3000

# El comando para encender tu servidor
CMD ["npx", "ts-node-dev", "src/server.ts"]